# Generated by Django 4.0.5 on 2022-06-05 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('num_response', models.IntegerField(default=0)),
                ('label_in_question', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('upvote_num', models.IntegerField(default=0)),
                ('account', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiscH_prototype.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_BOW',
            fields=[
                ('answer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer_category_num', models.CharField(max_length=40)),
                ('answer_justification', models.TextField(default='')),
                ('answer_upvote', models.IntegerField(default=0)),
                ('account_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiscH_prototype.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer_category_num', models.CharField(max_length=40)),
                ('answer_justification', models.TextField(default='')),
                ('answer_upvote', models.IntegerField(default=0)),
                ('account_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiscH_prototype.question')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('achievement_type', models.CharField(max_length=100)),
                ('achievement_date', models.DateField()),
                ('account_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
