# Generated by Django 4.0.4 on 2022-10-02 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscH_prototype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_justification',
            field=models.TextField(default='None'),
        ),
    ]
