# Generated by Django 4.0.4 on 2022-10-02 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscH_prototype', '0002_answer_date_alter_answer_answer_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_bow',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='answer_bow',
            name='answer_justification',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='answer_bow',
            name='answer_text_comment',
            field=models.TextField(default='None'),
        ),
    ]
