# Generated by Django 4.0.4 on 2022-10-02 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscH_prototype', '0003_answer_bow_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 22)),
        ),
        migrations.AlterField(
            model_name='answer_bow',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 12)),
        ),
    ]
