# Generated by Django 4.0.4 on 2022-10-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DiscH_prototype', '0004_alter_answer_date_alter_answer_bow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='question_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='DiscH_prototype.question'),
        ),
    ]
