# Generated by Django 4.0.4 on 2022-10-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscH_prototype', '0006_achievement_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='value',
            field=models.IntegerField(default=-1),
        ),
    ]
