# Generated by Django 4.0.4 on 2022-10-14 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscH_prototype', '0008_alter_answer_date_alter_answer_bow_date_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 4)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 4)),
        ),
        migrations.AlterField(
            model_name='answer_bow',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 24)),
        ),
    ]
