# Generated by Django 4.0.4 on 2022-10-14 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DiscH_prototype', '0009_comment_date_alter_answer_date_alter_answer_bow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='achievement',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='DiscH_prototype.achievement'),
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='DiscH_prototype.profile'),
        ),
    ]
