# Generated by Django 4.0.4 on 2022-10-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscH_prototype', '0011_remove_comment_achievement_remove_comment_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/profile/'),
        ),
    ]
