# Generated by Django 4.0.4 on 2023-01-01 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscH_prototype', '0012_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('question_id2', models.IntegerField(primary_key=True, serialize=False)),
                ('description2', models.TextField()),
                ('num_response2', models.IntegerField(default=0)),
                ('label_in_question2', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 22)),
        ),
        migrations.AlterField(
            model_name='answer_bow',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 12)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 22)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
