# Generated by Django 4.0.4 on 2023-01-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiscH_prototype', '0013_question2_alter_answer_date_alter_answer_bow_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question2',
            new_name='Question_select',
        ),
    ]
